name: mobile_test_task
description: Flutter Test.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  dio: ^5.4.1
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AlexandriaFLF
      fonts:
        - asset: assets/fonts/AlexandriaFLF.ttf
    - family: AlexandriaFLF-Bold
      fonts:
        - asset: assets/fonts/AlexandriaFLF-Bold.ttf
  
